name: 'Setup Node.js'
description: 'Setup Node.js 22 and install dependencies with cache'
inputs:
  working-directory:
    description: 'Package directory to run npm ci in'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-directory }}/node_modules
        key: ${{ runner.os }}-npm-${{ inputs.working-directory }}-${{ hashFiles(format('{0}/package-lock.json', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-npm-${{ inputs.working-directory }}-

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
