/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SignupConfirmRouteImport } from './routes/signup/confirm'
import { Route as AuthenticatedMeIndexRouteImport } from './routes/_authenticated/me/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedPostsIdRouteImport } from './routes/_authenticated/posts/$id'
import { Route as AuthenticatedMePasswordRouteImport } from './routes/_authenticated/me/password'
import { Route as AuthenticatedMeEmailRouteImport } from './routes/_authenticated/me/email'
import { Route as AuthenticatedCategoriesIdRouteImport } from './routes/_authenticated/categories/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupConfirmRoute = SignupConfirmRouteImport.update({
  id: '/signup/confirm',
  path: '/signup/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeIndexRoute = AuthenticatedMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPostsIdRoute = AuthenticatedPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMePasswordRoute = AuthenticatedMePasswordRouteImport.update({
  id: '/me/password',
  path: '/me/password',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeEmailRoute = AuthenticatedMeEmailRouteImport.update({
  id: '/me/email',
  path: '/me/email',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesIdRoute =
  AuthenticatedCategoriesIdRouteImport.update({
    id: '/categories/$id',
    path: '/categories/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup/confirm': typeof SignupConfirmRoute
  '/signup/': typeof SignupIndexRoute
  '/categories/$id': typeof AuthenticatedCategoriesIdRoute
  '/me/email': typeof AuthenticatedMeEmailRoute
  '/me/password': typeof AuthenticatedMePasswordRoute
  '/posts/$id': typeof AuthenticatedPostsIdRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/me/': typeof AuthenticatedMeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup/confirm': typeof SignupConfirmRoute
  '/signup': typeof SignupIndexRoute
  '/categories/$id': typeof AuthenticatedCategoriesIdRoute
  '/me/email': typeof AuthenticatedMeEmailRoute
  '/me/password': typeof AuthenticatedMePasswordRoute
  '/posts/$id': typeof AuthenticatedPostsIdRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/me': typeof AuthenticatedMeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup/confirm': typeof SignupConfirmRoute
  '/signup/': typeof SignupIndexRoute
  '/_authenticated/categories/$id': typeof AuthenticatedCategoriesIdRoute
  '/_authenticated/me/email': typeof AuthenticatedMeEmailRoute
  '/_authenticated/me/password': typeof AuthenticatedMePasswordRoute
  '/_authenticated/posts/$id': typeof AuthenticatedPostsIdRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/me/': typeof AuthenticatedMeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/signup/confirm'
    | '/signup/'
    | '/categories/$id'
    | '/me/email'
    | '/me/password'
    | '/posts/$id'
    | '/categories/'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/signup/confirm'
    | '/signup'
    | '/categories/$id'
    | '/me/email'
    | '/me/password'
    | '/posts/$id'
    | '/categories'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/signup/confirm'
    | '/signup/'
    | '/_authenticated/categories/$id'
    | '/_authenticated/me/email'
    | '/_authenticated/me/password'
    | '/_authenticated/posts/$id'
    | '/_authenticated/categories/'
    | '/_authenticated/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupConfirmRoute: typeof SignupConfirmRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/confirm': {
      id: '/signup/confirm'
      path: '/signup/confirm'
      fullPath: '/signup/confirm'
      preLoaderRoute: typeof SignupConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me/': {
      id: '/_authenticated/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthenticatedMeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts/$id': {
      id: '/_authenticated/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof AuthenticatedPostsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/password': {
      id: '/_authenticated/me/password'
      path: '/me/password'
      fullPath: '/me/password'
      preLoaderRoute: typeof AuthenticatedMePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/email': {
      id: '/_authenticated/me/email'
      path: '/me/email'
      fullPath: '/me/email'
      preLoaderRoute: typeof AuthenticatedMeEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories/$id': {
      id: '/_authenticated/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof AuthenticatedCategoriesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriesIdRoute: typeof AuthenticatedCategoriesIdRoute
  AuthenticatedMeEmailRoute: typeof AuthenticatedMeEmailRoute
  AuthenticatedMePasswordRoute: typeof AuthenticatedMePasswordRoute
  AuthenticatedPostsIdRoute: typeof AuthenticatedPostsIdRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedMeIndexRoute: typeof AuthenticatedMeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriesIdRoute: AuthenticatedCategoriesIdRoute,
  AuthenticatedMeEmailRoute: AuthenticatedMeEmailRoute,
  AuthenticatedMePasswordRoute: AuthenticatedMePasswordRoute,
  AuthenticatedPostsIdRoute: AuthenticatedPostsIdRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedMeIndexRoute: AuthenticatedMeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupConfirmRoute: SignupConfirmRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
